services:
  - type: web
    name: fastapi-app
    runtime: docker
    env: python
    buildCommand: docker build -t fastapi-app .
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
    healthCheckPath: /healthcheck

  - type: worker
    name: celery-worker
    runtime: docker
    env: python
    buildCommand: docker build -t celery-worker .
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString

databases:
  - name: redis
    databaseName: redis
    plan: free